<?php

/**
 * @file
 * Primary module hooks for Season Filter module.
 */

/**
 * Implements hook_help().
 */
function season_filter_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.season_filter':
      return '<p>' . t('Provides a views filter plugin for filtering entities by season based on field_date_from') . '</p>';
  }
}
